[book]
title = "Helio 101"
description = "todo todo todo todo todo"
authors = ["Peter Rudenko"]
multilingual = false
language = "en"
src = "."

[output.html]
default-theme = "navy"
curly-quotes = true
